server:
  port: ${PORT:8081}

spring:
  application:
    name: billing-service

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Set to update to allow Hibernate to create/update tables if needed
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always # Creates Spring Batch metadata tables automatically
    job:
      enabled: false            # Prevent all jobs from running on startup

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: billing-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.nwf.billing.dto.kafka

logging:
  level:
    root: DEBUG
    com.nwf.billing: DEBUG
    org.springframework.batch: INFO
